logging: 
  file: /logs/prototype-service.log
spring:
 zipkin: 
  baseUrl: http://localhost:9411
management: 
 security:
  enabled: false  
applicationProperties:
 message: welcome to prototype-21

 
 
  


