logging: 
  file: /logs/prototype-service.log
spring:
 zipkin: 
  baseUrl: http://30.135.52.141:9411
management: 
 security:
  enabled: false  
applicationProperties:
 message: welcome to prototype

 
 
  


